package com.codekrypt.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.codekrypt.greendao.db.LocalNote;

import com.codekrypt.greendao.db.LocalNoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localNoteDaoConfig;

    private final LocalNoteDao localNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localNoteDaoConfig = daoConfigMap.get(LocalNoteDao.class).clone();
        localNoteDaoConfig.initIdentityScope(type);

        localNoteDao = new LocalNoteDao(localNoteDaoConfig, this);

        registerDao(LocalNote.class, localNoteDao);
    }
    
    public void clear() {
        localNoteDaoConfig.clearIdentityScope();
    }

    public LocalNoteDao getLocalNoteDao() {
        return localNoteDao;
    }

}
