package com.codekrypt.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.codekrypt.greendao.db.LocalNote;
import com.codekrypt.greendao.db.ScreenInfo;

import com.codekrypt.greendao.db.LocalNoteDao;
import com.codekrypt.greendao.db.ScreenInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localNoteDaoConfig;
    private final DaoConfig screenInfoDaoConfig;

    private final LocalNoteDao localNoteDao;
    private final ScreenInfoDao screenInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localNoteDaoConfig = daoConfigMap.get(LocalNoteDao.class).clone();
        localNoteDaoConfig.initIdentityScope(type);

        screenInfoDaoConfig = daoConfigMap.get(ScreenInfoDao.class).clone();
        screenInfoDaoConfig.initIdentityScope(type);

        localNoteDao = new LocalNoteDao(localNoteDaoConfig, this);
        screenInfoDao = new ScreenInfoDao(screenInfoDaoConfig, this);

        registerDao(LocalNote.class, localNoteDao);
        registerDao(ScreenInfo.class, screenInfoDao);
    }
    
    public void clear() {
        localNoteDaoConfig.clearIdentityScope();
        screenInfoDaoConfig.clearIdentityScope();
    }

    public LocalNoteDao getLocalNoteDao() {
        return localNoteDao;
    }

    public ScreenInfoDao getScreenInfoDao() {
        return screenInfoDao;
    }

}
