package com.codekrypt.greendao.db;

import org.greenrobot.greendao.annotation.*;

import cpen391.team6.bored.Data.Note;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LOCAL_NOTE".
 */
@Entity
public class LocalNote extends Note {

    @Id
    private Long id;

    @NotNull
    private java.util.Date Date;

    @NotNull
    private String Title;
    private String Topic;

    @NotNull
    private String filePath;

    @Generated
    public LocalNote() {
    }

    public LocalNote(Long id) {
        this.id = id;
    }

    @Generated
    public LocalNote(Long id, java.util.Date Date, String Title, String Topic, String filePath) {
        this.id = id;
        this.Date = Date;
        this.Title = Title;
        this.Topic = Topic;
        this.filePath = filePath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public java.util.Date getDate() {
        return Date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(@NotNull java.util.Date Date) {
        this.Date = Date;
    }

    @NotNull
    public String getTitle() {
        return Title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String Title) {
        this.Title = Title;
    }

    public String getTopic() {
        return Topic;
    }

    public void setTopic(String Topic) {
        this.Topic = Topic;
    }

    @NotNull
    public String getFilePath() {
        return filePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilePath(@NotNull String filePath) {
        this.filePath = filePath;
    }

}
