package com.codekrypt.greendao.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import cpen391.team6.bored.BoredApplication;
import org.greenrobot.greendao.query.QueryBuilder;
// KEEP INCLUDES END

/**
 * Entity mapped to table "SCREEN_INFO".
 */
@Entity
public class ScreenInfo {
    private int Width;
    private int Height;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ScreenInfo() {
    }

    @Generated
    public ScreenInfo(int Width, int Height) {
        this.Width = Width;
        this.Height = Height;
    }

    public int getWidth() {
        return Width;
    }

    public void setWidth(int Width) {
        this.Width = Width;
    }

    public int getHeight() {
        return Height;
    }

    public void setHeight(int Height) {
        this.Height = Height;
    }

    // KEEP METHODS - put your custom methods here
    public static void saveInfo(int width, int height){
        ScreenInfoDao screenInfoDao = BoredApplication.getDaoSession().getScreenInfoDao();
        QueryBuilder<ScreenInfo> qb = screenInfoDao.queryBuilder();

        if(qb.list().isEmpty()){
            ScreenInfo screenInfo = new ScreenInfo(width, height);
            screenInfoDao.save(screenInfo);

        }else{

            /* Do Nothing, we have already saved the screen state */
        }

    }

    public static ScreenInfo getInfo(){

        ScreenInfoDao screenInfoDao = BoredApplication.getDaoSession().getScreenInfoDao();
        QueryBuilder<ScreenInfo> qb = screenInfoDao.queryBuilder();

        if(!qb.list().isEmpty()){
            return qb.list().get(0);

        }else{
            return null;
            /* Do Nothing, we have already saved the screen state */
        }
    }
    // KEEP METHODS END

}
