package com.codekrypt.greendao.db;

import org.greenrobot.greendao.annotation.*;
import org.greenrobot.greendao.query.QueryBuilder;

import cpen391.team6.bored.BoredApplication;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SCREEN_INFO".
 */
@Entity
public class ScreenInfo {
    private int Width;
    private int Height;

    @Generated
    private ScreenInfo() {
    }

    public static void saveInfo(int width, int height){
        ScreenInfoDao screenInfoDao = BoredApplication.getDaoSession().getScreenInfoDao();
        QueryBuilder<ScreenInfo> qb = screenInfoDao.queryBuilder();

        if(qb.list().isEmpty()){
            ScreenInfo screenInfo = new ScreenInfo(width, height);
            screenInfoDao.save(screenInfo);

        }else{

            /* Do Nothing, we have already saved the screen state */
        }

    }

    public static ScreenInfo getInfo(){

        ScreenInfoDao screenInfoDao = BoredApplication.getDaoSession().getScreenInfoDao();
        QueryBuilder<ScreenInfo> qb = screenInfoDao.queryBuilder();

        if(!qb.list().isEmpty()){
            return qb.list().get(0);

        }else{
            return null;
            /* Do Nothing, we have already saved the screen state */
        }
    }

    @Generated
    public ScreenInfo(int Width, int Height) {
        this.Width = Width;
        this.Height = Height;
    }

    public int getWidth() {
        return Width;
    }

    public void setWidth(int Width) {
        this.Width = Width;
    }

    public int getHeight() {
        return Height;
    }

    public void setHeight(int Height) {
        this.Height = Height;
    }

}
