package com.codekrypt.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCREEN_INFO".
*/
public class ScreenInfoDao extends AbstractDao<ScreenInfo, Void> {

    public static final String TABLENAME = "SCREEN_INFO";

    /**
     * Properties of entity ScreenInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Width = new Property(0, int.class, "Width", false, "WIDTH");
        public final static Property Height = new Property(1, int.class, "Height", false, "HEIGHT");
    }


    public ScreenInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ScreenInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCREEN_INFO\" (" + //
                "\"WIDTH\" INTEGER NOT NULL ," + // 0: Width
                "\"HEIGHT\" INTEGER NOT NULL );"); // 1: Height
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCREEN_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ScreenInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getWidth());
        stmt.bindLong(2, entity.getHeight());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ScreenInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getWidth());
        stmt.bindLong(2, entity.getHeight());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ScreenInfo readEntity(Cursor cursor, int offset) {
        ScreenInfo entity = new ScreenInfo( //
            cursor.getInt(offset + 0), // Width
            cursor.getInt(offset + 1) // Height
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ScreenInfo entity, int offset) {
        entity.setWidth(cursor.getInt(offset + 0));
        entity.setHeight(cursor.getInt(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ScreenInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ScreenInfo entity) {
        return null;
    }

    @Override
    public boolean hasKey(ScreenInfo entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
